#!/bin/bash

# Ndal scriptin nëse ndodh error
set -e

# Folderi që dëshiron të bësh backup
SOURCE_DIR="$HOME/repositories/Devops-Course/rony/Eronsalihu/Manual-folder"

# Folderi ku do ruhen backup-et
DEST_DIR="$HOME/repositories/Devops-Course/rony/Eronsalihu/New-folder"

# Krijon folderin e backup nëse nuk ekziston
mkdir -p "$DEST_DIR"

# Emri i backup file me datë dhe orë
BACKUP_FILE="backup_$(date +%F_%H-%M-%S).tar.gz"

# Krijon backup të kompresuar
tar -czf "$DEST_DIR/$BACKUP_FILE" -C "$HOME/repositories/Devops-Course/rony/Eronsalihu" "Manual-folder"


# Mesazh përfundimi
echo "Backup completed successfully"
echo "Backup saved at: $DEST_DIR/$BACKUP_FILE"
