#!/bin/bash

SOURCE_DIR="Manual-folder"
DEST_DIR="backup"

mkdir -p "$DEST_DIR"

BACKUP_FILE="backup_$(date +%F_%H-%M-%S).tar.gz"

tar -czf "$DEST_DIR/$BACKUP_FILE" "$SOURCE_DIR"

echo "Backup completed successfully"
echo "Backup saved in: $DEST_DIR/$BACKUP_FILE"
