name: Test CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests and save logs
        run: npm test > dist/test-log.txt

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: dist/test-log.txt
